// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/auth/auth.vue')['default']
    AuthAll: typeof import('./src/components/auth/authAll.vue')['default']
    Auths: typeof import('./src/components/auth/auths.vue')['default']
    Cropper: typeof import('./src/components/cropper/index.vue')['default']
    Editor: typeof import('./src/components/editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    IconSelector: typeof import('./src/components/iconSelector/index.vue')['default']
    List: typeof import('./src/components/iconSelector/list.vue')['default']
    NoticeBar: typeof import('./src/components/noticeBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
    Table: typeof import('./src/components/table/index.vue')['default']
  }
}
