name: "business-manage-web Project Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
          tag_prefix: v

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
        with:
          persist-credentials: false
      - name: Install And Build
        run: |
          npx pnpm install
          npm run build
          pwd
          ls -al

#      - name: Update Project Version
#        run: |
#          npm version patch
#          cat ./package.json
#          export ver=$(cat ./package.json | grep -e '"version":' | tr -cd "[0-9].")
#          echo $ver
#          echo "${{ secrets.ACCESS_TOKEN }}"
#
#          rm -rf ./git
#          git init
#          git config --global user.email "imchrisorz@gmail.com"
#          git config --global user.name "imchrisorz"
#          git remote add origin https://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@github.com/ImChrisChen/business-manage-web.git
#          git commit -a -m "ci: 版本发布,当前版本:${ver}"
#          git push origin master

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: imchrisorz
          password: dckr_pat_UUoUPBvOuTi1_RQWsjdbqSUiZOA
      - name: Build Docker Image And Push Image
        run: |
          bash ./scripts/release.sh