name: "business-manage-web Project Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Install And Build
        run: |
          npx pnpm install
          npm run build
          pwd
          ls -al


      - name: Create local Changes
        run: |
          ls -al
          git status
          git --no-pager log
          cat ./package.json
          pwd

          git config --global user.email "imchrisorz@gmail.com"
          git config --global user.name "github-actions[bot]"
          
          npm version patch
          ver=$(cat ./package.json | grep -e '"version":' | tr -cd "[0-9].")
          echo "${{ secrets.ACCESS_TOKEN }}"
          echo "project_version=$ver" >> $GITHUB_ENV
          
      - name: Commit & Push Changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: 'imchrisorz@gmail.com'
          author_name: 'github-actions[bot]'
          amend: true
          message: "chore(ci/cd): 自动化构建,当前项目版本:${{ env.project_version }}"
          branch: 'main'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: imchrisorz
          password: {{ secrets.DOCKER_SECRET }}

      - name: Build Docker Image And Push Image
        run: |
          bash ./scripts/release.sh