name: "business-manage-web Project Build"

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main


jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.6.0
        with:
          persist-credentials: false

      - name: Update Project Version
        run: |
          git config --local user.email "imchrisorz@gmail.com"
          git config --local user.name "github_ci_bot"
          
          current_branch_name=$(git symbolic-ref --short HEAD)
          npm version patch
          ver=$(cat ./package.json | grep -e '"version":' | tr -cd "[0-9].")
          git add .
          git commit -m "ci: 版本发布,当前版本:${ver}"
          git tag -a "v${ver}" -m "v${ver}"
      #          git push origin "origin/${current_branch_name}"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: ${{ github.head_ref }}
          tags: true

      - name: Install And Build
        run: |
          npx pnpm install
          npm run build
          pwd
          ls -al

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: imchrisorz
          password: dckr_pat_UUoUPBvOuTi1_RQWsjdbqSUiZOA

      - name: Build Docker Image And Push Image
        run: | 
          bash ./scripts/release.sh