name: "business-manage-web Project Build"

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main


jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.6.0
        with:
          persist-credentials: false

      - name: Install And Build
        run: |
          npx pnpm install
          npm run build
          pwd
          ls -al

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: imchrisorz
          password: dckr_pat_UUoUPBvOuTi1_RQWsjdbqSUiZOA

      - name: Build Docker Image
        run: | 
          bash ./scripts/release.sh