name: "business-manage-web Project Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Install And Build
        run: |
          npx pnpm install
          npm run build
          pwd
          ls -al


      - name: Create local Changes
        run: |
          npm version patch
          ver=$(cat ./package.json | grep -e '"version":' | tr -cd "[0-9].")
          echo "::set-env name=project_version::$ver"

      - name: Commit & Push Changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: 'imchrisorz@gmail.com'
          author_name: 'github-actions[bot]'
          message: "chore: 自动化构建,当前版本: ${{env.project_version}}"
          branch: 'main'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: imchrisorz
          password: dckr_pat_UUoUPBvOuTi1_RQWsjdbqSUiZOA

      - name: Build Docker Image And Push Image
        run: |
          bash ./scripts/release.sh